spring:
  application:
    name: MeasureManager
  jpa:
    hibernate:
      ddl-auto: create-drop



  security:
    oauth2:
      resourceserver:
        jwt:
          #issuer-uri: http://172.20.0.22:8080/realms/measurestream
          issuer-uri: http://localhost:8090/realms/measurestream
server:
  port: 8080

