-- Baseline: schema del database SENSORS sulla Raspberry Pi al 14/09/2026,
-- ricavato con pg_dump --schema-only --no-owner --no-privileges.
--
-- Sulla Pi questa migrazione NON viene eseguita: il database esiste già e
-- spring.flyway.baseline-on-migrate registra la versione 1 come baseline.
-- Serve a creare lo stesso schema su un database vuoto (sviluppo, test).
--
-- Rispetto al dump sono state tolte solo le righe \restrict / \unrestrict
-- (comandi di psql, non SQL) e le impostazioni di sessione SET / set_config.
-- I DEFAULT di ac_powered, is_charging e config_version sono quelli presenti
-- sulla Pi, aggiunti a mano quando le colonne sono state create.

CREATE TABLE public.app_user (
    user_id character varying(255) NOT NULL,
    email character varying(255),
    name character varying(255),
    role character varying(255),
    surname character varying(255)
);

CREATE TABLE public.control_unit (
    id bigint NOT NULL,
    maxmu integer NOT NULL,
    bandwidth integer NOT NULL,
    coding_rate character varying(255),
    data_rate integer NOT NULL,
    dev_eui bigint NOT NULL,
    device_id character varying(255),
    frequency integer NOT NULL,
    hasgps boolean NOT NULL,
    last_airtime double precision NOT NULL,
    last_seen timestamp(6) without time zone,
    location bytea,
    model integer NOT NULL,
    name character varying(255) NOT NULL,
    polling_interval integer NOT NULL,
    remaining_battery double precision NOT NULL,
    rssi double precision NOT NULL,
    semantic_location character varying(255),
    setting1 integer NOT NULL,
    spreading_factor integer NOT NULL,
    status integer NOT NULL,
    transmission_interval integer NOT NULL,
    transmission_power integer NOT NULL,
    useddc integer NOT NULL,
    used_daily_airtime bigint NOT NULL,
    user_user_id character varying(255),
    lastfcnt integer,
    ac_powered boolean DEFAULT false,
    is_charging boolean DEFAULT false,
    config_version bigint DEFAULT 0,
    CONSTRAINT control_unit_remaining_battery_check CHECK ((remaining_battery <= (100)::double precision))
);

CREATE SEQUENCE public.control_unit_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE public.measurement_unit (
    id bigint NOT NULL,
    extended_id bigint,
    local_id integer NOT NULL,
    model integer NOT NULL,
    control_unit_id bigint,
    user_user_id character varying(255)
);

CREATE SEQUENCE public.measurement_unit_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE public.measurements (
    id bigint NOT NULL,
    measurement_type character varying(50),
    "timestamp" timestamp(6) with time zone NOT NULL,
    value_primary double precision,
    value_secondary double precision,
    sensor_id bigint NOT NULL
);

ALTER TABLE public.measurements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.measurements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.sensor (
    id bigint NOT NULL,
    cal_date bigint,
    cal_initials character varying(250),
    coeffa double precision,
    coeffb double precision,
    coeffc double precision,
    coeffd double precision,
    elec_val double precision NOT NULL,
    is_flash_active boolean NOT NULL,
    is_lower_threshold_active boolean NOT NULL,
    is_lower_threshold_min boolean NOT NULL,
    is_sensor_active boolean NOT NULL,
    is_statistic_active boolean NOT NULL,
    is_upper_threshold_active boolean NOT NULL,
    is_upper_threshold_max boolean NOT NULL,
    meas_loc_id bigint,
    model_name character varying(255),
    phy_threshold double precision NOT NULL,
    phys_val double precision NOT NULL,
    samplingf double precision NOT NULL,
    sampling_period integer NOT NULL,
    sensor_index integer NOT NULL,
    setting1 integer NOT NULL,
    mu_id bigint,
    configuration_measure character varying(255)
);

CREATE SEQUENCE public.sensor_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE public.signal_qualities (
    id bigint NOT NULL,
    airtime double precision,
    data_rate integer,
    rssi double precision,
    snr double precision,
    "timestamp" timestamp(6) with time zone NOT NULL,
    control_unit_id bigint NOT NULL
);

ALTER TABLE public.signal_qualities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.signal_qualities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_pkey PRIMARY KEY (user_id);

ALTER TABLE ONLY public.control_unit
    ADD CONSTRAINT control_unit_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.measurement_unit
    ADD CONSTRAINT measurement_unit_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.measurements
    ADD CONSTRAINT measurements_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.sensor
    ADD CONSTRAINT sensor_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.signal_qualities
    ADD CONSTRAINT signal_qualities_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.control_unit
    ADD CONSTRAINT ukbiqdue5dycsfiiqbqimgye4kr UNIQUE (dev_eui);

ALTER TABLE ONLY public.measurement_unit
    ADD CONSTRAINT ukj3v4bbq12qsukddjuimfpd34n UNIQUE (extended_id);

CREATE INDEX idx_measurements_sensor_time ON public.measurements USING btree (sensor_id, "timestamp" DESC);

CREATE INDEX idx_measurements_type_time ON public.measurements USING btree (measurement_type, "timestamp" DESC);

CREATE INDEX idx_signal_cu_time ON public.signal_qualities USING btree (control_unit_id, "timestamp" DESC);

CREATE INDEX idx_signal_time ON public.signal_qualities USING btree ("timestamp" DESC);

ALTER TABLE ONLY public.signal_qualities
    ADD CONSTRAINT fk2jrupdbruhbk2ce54s1dj4ybr FOREIGN KEY (control_unit_id) REFERENCES public.control_unit(id);

ALTER TABLE ONLY public.measurement_unit
    ADD CONSTRAINT fkau01wc8r0vqlgmk1nc9rdiolw FOREIGN KEY (user_user_id) REFERENCES public.app_user(user_id);

ALTER TABLE ONLY public.measurements
    ADD CONSTRAINT fkekarcli1a5y324d3n946b89vu FOREIGN KEY (sensor_id) REFERENCES public.sensor(id);

ALTER TABLE ONLY public.control_unit
    ADD CONSTRAINT fkh0i6kgw5vwn2w2u2npcpubiwi FOREIGN KEY (user_user_id) REFERENCES public.app_user(user_id);

ALTER TABLE ONLY public.sensor
    ADD CONSTRAINT fkhgvo4dtxyn8id7iv9bqs4u5us FOREIGN KEY (mu_id) REFERENCES public.measurement_unit(id);

ALTER TABLE ONLY public.measurement_unit
    ADD CONSTRAINT fkibdr1jysapr6vju963mpowbyx FOREIGN KEY (control_unit_id) REFERENCES public.control_unit(id);
