-- Registro dei template (passo 6).
-- Una tabella sola: cio' su cui si filtra diventa colonna, il template resta un documento
-- in jsonb. Aggiungere un campo a un template non genera nessuna migrazione.

CREATE TABLE public.template (
    id              bigint      NOT NULL,
    kind            varchar(16) NOT NULL,   -- sensor | reference | mu | cu | protocol
    key_id          integer     NOT NULL,   -- templateId, modello di MU/CU, ProtocolVer
    major           integer     NOT NULL,
    minor           integer     NOT NULL,
    patch           integer     NOT NULL,
    status          varchar(16) NOT NULL,   -- DEV | PUBLISHED | REVOKED
    model_name      varchar(255),
    schema_version  varchar(32),
    content         jsonb       NOT NULL,
    content_hash    varchar(64) NOT NULL,   -- SHA-256 del contenuto normalizzato
    source          varchar(32) NOT NULL,   -- seed | api | ci
    published_by    varchar(255),
    published_at    timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT template_pkey PRIMARY KEY (id),
    CONSTRAINT template_version_unique UNIQUE (kind, key_id, major, minor, patch)
);

ALTER TABLE public.template ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.template_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

-- Risoluzione (kind, key_id, MAJOR) -> versione piu' alta dentro quel MAJOR.
CREATE INDEX idx_template_resolve ON public.template (kind, key_id, major, status);

-- Il ponte con sensor.model_name, finche' il DTO porta il nome invece del riferimento.
CREATE INDEX idx_template_model_name ON public.template (lower(model_name));
