-- Registro dei frame ricevuti: il grezzo e il decodificato, sempre entrambi.
--
-- Finora un report che non si riusciva a interpretare spariva lasciando una riga di log.
-- Qui resta: il payload com'e' arrivato, il risultato della decodifica quando c'e' stata, e
-- il motivo per cui e' stato scartato quando non c'e' stata. Serve a tre cose che prima non
-- si potevano fare: contare quanto si perde, capire perche', e rileggere un frame in seguito
-- con la configurazione giusta.

CREATE TABLE public.uplink_frame (
    id              bigint      NOT NULL,
    control_unit_id bigint,
    dev_eui         bigint      NOT NULL,
    received_at     timestamptz NOT NULL DEFAULT now(),
    fport           integer,
    -- CFG_VER dichiarato dal frame e quello che il server considerava attivo: la coppia
    -- dice di quanto erano disallineati nel momento esatto in cui il report e' arrivato.
    cfg_version     integer,
    expected_cfg_version integer,
    raw_payload     text        NOT NULL,   -- base64, esattamente come arrivato da TTN
    decoded         jsonb,                  -- null se la decodifica non e' stata fatta
    status          varchar(32) NOT NULL,   -- DECODED | DISCARDED_CFG_MISMATCH | DISCARDED_DECODE_ERROR
    failure_reason  text,
    -- L'utente ha preso atto del problema: il conteggio riparte da zero, il frame resta.
    acknowledged_at timestamptz,
    CONSTRAINT uplink_frame_pkey PRIMARY KEY (id),
    CONSTRAINT uplink_frame_control_unit_fk
        FOREIGN KEY (control_unit_id) REFERENCES public.control_unit(id) ON DELETE SET NULL
);

ALTER TABLE public.uplink_frame ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.uplink_frame_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

-- Le due letture che si fanno davvero: lo storico di una CU, e la pulizia per anzianita'.
CREATE INDEX idx_uplink_frame_cu_time ON public.uplink_frame (control_unit_id, received_at DESC);
CREATE INDEX idx_uplink_frame_received ON public.uplink_frame (received_at);

-- Report scartati perche' non decodificabili: byte mancanti, payload corrotto, sensori non
-- corrispondenti. Affianca config_mismatch_count, che conta il disallineamento di versione.
ALTER TABLE public.control_unit
    ADD COLUMN decode_failure_count bigint NOT NULL DEFAULT 0;
