-- Una riga per metrica, al posto di due colonne generiche.
--
-- La tabella `measurements` aveva value_primary e value_secondary, il cui significato
-- dipendeva da una stringa: in 'avg-std' la prima era la media, in 'max-min' il massimo.
-- Il report v1.2 porta fino a undici metriche per sensore (ordine canonico, capitolo 4.6),
-- e tre di loro - mediana, percentile alto, percentile basso - non stanno in una coppia.
--
-- Qui ogni metrica e' una riga con il suo nome. La metrica dodicesima, quando arrivera',
-- non richiede ne' migrazione ne' pannelli nuovi.

CREATE TABLE public.metric_sample (
    id              bigint      NOT NULL,
    sensor_id       bigint      NOT NULL,
    "timestamp"     timestamptz NOT NULL,
    -- Nome dell'ordine canonico: mean, variance, max, min, integral, tot_h, tot_l,
    -- median, p_high, p_low, zcr. 'punctual' e' l'unico nome locale, ereditato dalle
    -- righe storiche che non venivano da quella tabella.
    metric          varchar(16) NOT NULL,
    -- Valore come lo usa l'interfaccia. Quando la conversione non c'e' ancora (varianza di
    -- una curva non lineare, integrale, max e min) qui finisce comunque il numero letto:
    -- `converted` dice se e' una grandezza fisica o una lettura elettrica.
    value           double precision,
    -- Il valore grezzo come e' arrivato sul filo, quando lo si conosce: permette di
    -- riconvertire senza rileggere il frame se la formula cambia.
    raw_value       double precision,
    converted       boolean,
    -- Versione esatta del template con cui e' stata decodificata: e' il principio del
    -- registro, ogni risultato porta con se' la versione che ha vinto la risoluzione.
    template_version varchar(16),
    -- Da quale frame arriva: traccia completa dal byte alla misura.
    uplink_frame_id bigint,
    CONSTRAINT metric_sample_pkey PRIMARY KEY (id),
    CONSTRAINT metric_sample_sensor_fk
        FOREIGN KEY (sensor_id) REFERENCES public.sensor(id) ON DELETE CASCADE,
    CONSTRAINT metric_sample_frame_fk
        FOREIGN KEY (uplink_frame_id) REFERENCES public.uplink_frame(id) ON DELETE SET NULL
);

ALTER TABLE public.metric_sample ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.metric_sample_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

-- La lettura che fanno i grafici: un sensore, una metrica, un intervallo di tempo.
CREATE INDEX idx_metric_sample_sensor_metric_time
    ON public.metric_sample (sensor_id, metric, "timestamp" DESC);

-- ---------------------------------------------------------------------------
-- Le righe storiche, convertite una a una.
-- `measurements` non viene toccata: resta come rete di sicurezza finche' non si e' certi
-- che tutto legga dalla tabella nuova. Da quel momento in poi nessuno ci scrive piu'.
-- converted resta NULL sullo storico: prima del 14/09/2026 la conversione non girava
-- affatto, dopo si', e distinguerlo riga per riga non e' possibile con certezza.
-- ---------------------------------------------------------------------------

INSERT INTO public.metric_sample (sensor_id, "timestamp", metric, value)
SELECT sensor_id, "timestamp",
       CASE measurement_type
           WHEN 'max-min'  THEN 'max'
           WHEN 'integral' THEN 'integral'
           WHEN 'puntual'  THEN 'punctual'
           ELSE 'mean'
       END,
       value_primary
FROM public.measurements
WHERE value_primary IS NOT NULL;

INSERT INTO public.metric_sample (sensor_id, "timestamp", metric, value)
SELECT sensor_id, "timestamp",
       CASE measurement_type WHEN 'max-min' THEN 'min' ELSE 'variance' END,
       value_secondary
FROM public.measurements
WHERE value_secondary IS NOT NULL
  AND measurement_type IN ('avg-std', 'average-std', 'max-min');

-- ---------------------------------------------------------------------------
-- Viste per Grafana.
--
-- I pannelli contengono la query scritta dentro e conoscono lo schema fisico: qualunque
-- modifica li svuota in silenzio. Con una vista in mezzo lo schema puo' cambiare, si
-- aggiorna la vista una volta sola e i pannelli non se ne accorgono.
--
-- Le viste riproducono esattamente la forma che i pannelli usano oggi, quindi la
-- migrazione dei pannelli e' una riscrittura della sola clausola FROM.
-- ---------------------------------------------------------------------------

CREATE SCHEMA IF NOT EXISTS grafana;

CREATE VIEW grafana.measure_avg_std AS
SELECT m.sensor_id,
       m."timestamp" AS "time",
       MAX(CASE WHEN m.metric = 'mean' THEN m.value END)     AS media,
       MAX(CASE WHEN m.metric = 'variance' THEN m.value END) AS deviazione_standard
FROM public.metric_sample m
WHERE m.metric IN ('mean', 'variance')
GROUP BY m.sensor_id, m."timestamp";

CREATE VIEW grafana.measure_max_min AS
SELECT m.sensor_id,
       m."timestamp" AS "time",
       MAX(CASE WHEN m.metric = 'max' THEN m.value END) AS max,
       MAX(CASE WHEN m.metric = 'min' THEN m.value END) AS min
FROM public.metric_sample m
WHERE m.metric IN ('max', 'min')
GROUP BY m.sensor_id, m."timestamp";

CREATE VIEW grafana.measure_integral AS
SELECT sensor_id, "timestamp" AS "time", value AS integral_value
FROM public.metric_sample
WHERE metric = 'integral';

CREATE VIEW grafana.measure_punctual AS
SELECT sensor_id, "timestamp" AS "time", value AS valore_puntuale
FROM public.metric_sample
WHERE metric = 'punctual';

-- L'utente di Grafana legge le viste, non le tabelle. Il GRANT e' condizionato perche'
-- l'utente in sola lettura e' facoltativo e potrebbe non esistere ancora.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'grafana_ro') THEN
        GRANT USAGE ON SCHEMA grafana TO grafana_ro;
        GRANT SELECT ON ALL TABLES IN SCHEMA grafana TO grafana_ro;
    END IF;
END $$;
