-- Protocollo v1.2, lato downlink: numero di comando e istantanee di configurazione.

-- CMD_SEQ: numero del comando, nel prologo di blocco dei comandi 0x21-0x24. Se il server
-- ritrasmette, la CU riconosce il duplicato e non applica due volte una configurazione.
-- Viaggia su un byte e va in wrap a 255, come CFG_VER.
ALTER TABLE public.control_unit
    ADD COLUMN cmd_seq integer NOT NULL DEFAULT 0;

-- L'istantanea della configurazione al momento in cui CFG_VER e' stato incrementato.
--
-- Serve a leggere un report che arriva con un CFG_VER vecchio: senza, quei byte non sono
-- interpretabili perche' non si sa piu' quali slot fossero attivi e con quali metriche.
-- Con l'istantanea il report si decodifica con la configurazione di allora invece di essere
-- scartato, ed e' il motivo per cui la tabella esiste.
CREATE TABLE public.config_snapshot (
    id              bigint      NOT NULL,
    control_unit_id bigint      NOT NULL,
    cfg_version     bigint      NOT NULL,
    taken_at        timestamptz NOT NULL DEFAULT now(),
    -- Per ogni slot: indice globale, sensore, metriche attive, periodo di campionamento.
    content         jsonb       NOT NULL,
    CONSTRAINT config_snapshot_pkey PRIMARY KEY (id),
    CONSTRAINT config_snapshot_unique UNIQUE (control_unit_id, cfg_version),
    CONSTRAINT config_snapshot_cu_fk
        FOREIGN KEY (control_unit_id) REFERENCES public.control_unit(id) ON DELETE CASCADE
);

ALTER TABLE public.config_snapshot ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.config_snapshot_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

-- La ricerca vera: «quale configurazione aveva questa CU quando il suo CFG_VER valeva N?».
-- Il confronto avviene sul byte basso, perche' e' quello che viaggia sul filo.
CREATE INDEX idx_config_snapshot_lookup
    ON public.config_snapshot (control_unit_id, (cfg_version % 256));
