-- Allarmi 0xA0 ed eventi 0xA2 (capitoli 4.10 e 4.11 della documentazione v1.2).
--
-- Due canali distinti, e la distinzione non e' formale. Un allarme e' una condizione della
-- grandezza misurata: ha un'attivazione e un rientro, resta latchato, e chi lo riceve deve
-- poterci reagire. Un evento e' un fatto accaduto al dispositivo: ha un istante, non ha un
-- rientro, e serve a capire cosa e' successo. Due tabelle, quindi, non una con un tipo.

CREATE TABLE public.sensor_alarm (
    id              bigint      NOT NULL,
    control_unit_id bigint,
    sensor_id       bigint,
    received_at     timestamptz NOT NULL DEFAULT now(),
    -- ALARM_SEQ del messaggio: il server rileva gli allarmi persi confrontandolo con quello
    -- riportato nel poll.
    alarm_seq       integer,
    -- Indirizzo del canale come arriva sul filo, utile anche quando il sensore non e' noto.
    local_id        integer     NOT NULL,
    sensor_index    integer     NOT NULL,
    -- 0 = condizione attivata, 1 = rientrata (bit EVT del byte # Sensore).
    cleared         boolean     NOT NULL DEFAULT false,
    -- La parola di allarme completa, catena di estensione inclusa, come numero.
    alarm_word      bigint      NOT NULL,
    -- Le condizioni riconosciute, gia' risolte: una riga di testo per bit alzato.
    conditions      jsonb,
    -- Valore corrente del sensore al momento dell'allarme, nella forma dei report.
    raw_value       integer,
    value           double precision,
    acknowledged_at timestamptz,
    CONSTRAINT sensor_alarm_pkey PRIMARY KEY (id),
    CONSTRAINT sensor_alarm_cu_fk
        FOREIGN KEY (control_unit_id) REFERENCES public.control_unit(id) ON DELETE CASCADE,
    CONSTRAINT sensor_alarm_sensor_fk
        FOREIGN KEY (sensor_id) REFERENCES public.sensor(id) ON DELETE SET NULL
);

ALTER TABLE public.sensor_alarm ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sensor_alarm_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE INDEX idx_sensor_alarm_cu_time ON public.sensor_alarm (control_unit_id, received_at DESC);

CREATE TABLE public.device_event (
    id              bigint      NOT NULL,
    control_unit_id bigint,
    sensor_id       bigint,
    received_at     timestamptz NOT NULL DEFAULT now(),
    event_seq       integer,
    -- Local ID della MU che ha generato l'evento; 0 indica la CU stessa.
    source          integer     NOT NULL,
    -- Indice del sensore nel modello di MU; 255 (0xFF) quando riguarda il dispositivo.
    sensor_index    integer     NOT NULL,
    code            integer     NOT NULL,
    param           integer,
    -- Il byte di eta' come e' arrivato, e l'istante che se ne ricava. La codifica e' non
    -- lineare e porta con se' un'incertezza di quantizzazione, che va conservata: un evento
    -- a 71 non e' «due ore fa», e' «due ore fa piu' o meno cinque minuti».
    age_raw         integer,
    occurred_at     timestamptz,
    age_uncertainty_seconds integer,
    -- Testo risolto: dalla tabella dei codici MeasureStream o dal template del costruttore.
    description     text,
    acknowledged_at timestamptz,
    CONSTRAINT device_event_pkey PRIMARY KEY (id),
    CONSTRAINT device_event_cu_fk
        FOREIGN KEY (control_unit_id) REFERENCES public.control_unit(id) ON DELETE CASCADE,
    CONSTRAINT device_event_sensor_fk
        FOREIGN KEY (sensor_id) REFERENCES public.sensor(id) ON DELETE SET NULL
);

ALTER TABLE public.device_event ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.device_event_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE INDEX idx_device_event_cu_time ON public.device_event (control_unit_id, received_at DESC);

-- ALARM_SEQ ed EVENT_SEQ dell'ultimo messaggio ricevuto: il confronto con quelli riportati
-- nel poll dice se per strada se n'e' perso qualcuno.
ALTER TABLE public.control_unit
    ADD COLUMN last_alarm_seq integer,
    ADD COLUMN last_event_seq integer;
